version: "3.4"

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
    user: 1000:1000
    command:
      - sh
      - -c
      - "/usr/bin/composer install && php-fpm -F"
    volumes:
      - .:/var/www/project
