version: "3.4"

services:

  # nginx
  nginx:
    image: nginx:stable-alpine
    ports:
      - "81:80"
    volumes:
      - .:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # php
  php:
    build:
      context: .
    user: 1000:1000
    command:
      - sh
      - -c
      - "/usr/bin/composer install && php-fpm -F"
    volumes:
      - .:/var/www/project
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
